### ISSUE TITLE
hook failed: "install"

### ISSUE THREAD

**Issue by extraymond** [cmars/juju-charm-gogs#9]
Hi! I would like to install gogs on my google cloud, but got a fail report.

**Comment by cmars** [comment]
Can you paste the logs from /var/log/juju on the unit?

**Comment by extraymond** [comment]
[unit-gogs-1.txt](https://github.com/cmars/juju-charm-gogs/files/1185140/unit-gogs-1.txt)

This is the log.

**Comment by extraymond** [comment]
Is this sufficient for debug?

**Comment by cmars** [comment]
Yes, looks like the download link is no longer valid. I'm going to update the charm to use a resource instead.

**Comment by cmars** [comment]
@extraymond Please try deploying cs:~cmars/gogs-12.

**Comment by extraymond** [comment]
Thx, it's working wonderfully.

Casey Marshall 於 2017/8/4 下午12:46 寫道:
